=== ggniame/xml-actu/actu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
     <xs:element name="actu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="breve" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titre" type="xs:string"/>
                            <xs:element name="texte" type="xs:string"/>
                            <xs:element name="photo" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="src" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="url" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="href" type="xs:anyURI" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="theme" type="xs:string" use="required"/>
                        <xs:attribute name="langue" type="xs:string" use="required"/>
                        <xs:attribute name="date" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ggniame/xml-actu/actu.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="actu.xsl"?>
<actu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="actu.xsd">
<breve theme="actu" langue="fr" date="7 décembre 2004">
<titre>Les députés renoncent au CV anonyme</titre>
<texte> Les députés ont achevé lundi, après plus de deux semaines de débat marathon, l'examen du projet de loi de cohésion sociale. Ils ont abandonné le CV anonyme, mesure à laquelle le gouvernement et l'UMP étaient hostiles en l'état. </texte>
<url href="http://www.reuters.fr/locales/c_newsArticle.jsp?type=topNews;localeKey=fr_FR;storyID=7007458">Reuters</url>
<url href="http://news.tf1.fr/news/economie/0,,3189581,00.html">TF1</url>
</breve>
<breve theme="sport" langue="fr" date="7 décembre 2004">
<titre>Décès de Raymond Goethals</titre>
<texte> L'entraîneur belge Raymond Goethals, décédé lundi à Bruxelles, suscitait la sympathie grâce à une truculence et une gouaille incomparables qui en faisaient un bon client des médias. </texte>
<photo src="http://robert93.free.fr/staff/goethals01.jpg"/>
<url href="http://www.reuters.fr/locales/c_newsArticle.jsp?type=sportsNews;localeKey=fr_FR;storyID=7007386">Reuters</url>
</breve>
<breve theme="actu" langue="fr" date="7 février 2006">
<titre>Mobilisation contre le CPE</titre>
<texte> Manifestations en ce moment dans toutes les grandes villes de France. </texte>
</breve>
</actu>
